name: build svelte

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies Python
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Clone Index
        run: python clone-index.py

      - name: Generate sitemap
        run: python generate-sitemap.py

      - name: Pecah JSON
        run: python pecah-json.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
